import { Metadata } from "next";

// export const metadata:Metadata = {
// 	title: "Next.js",
// 	description: "Generated by Next.js",
// };

export function generateMetadata(): Metadata {
	// 비동기 통신의 결과를 메타데이터의 정보로 활용할 수 있다.
	return {
		title: "Next.js",
		description: "Generated by Next.js",
	};
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ko">
			<body>{children}</body>
		</html>
	);
}
