import { Metadata } from "next";
import { Noto_Sans_KR, Anton } from "next/font/google";
import { Doldam } from "@/public/fonts/local_fonts";

export const notoSansKR = Noto_Sans_KR({ weight: "variable" }); // subset??...
export const anton = Anton({ weight: "400" }); // subset??...
export const doldam = Doldam;

export const metadata: Metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ko">
			<body>{children}</body>
		</html>
	);
}
